export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const CREATE_SUCCESS = 'CREATE_SUCCESS';
export const ERROR_RESET = 'ERROR_RESET';

export const SET_MOTORCARRIER = 'SET_MOTORCARRIER';


export const GET_USERS_START = 'GET_USERS_START';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';

export const GET_VEHICLES_START = 'GET_VEHICLES_START';
export const GET_VEHICLES_SUCCESS = 'GET_VEHICLES_SUCCESS';
export const GET_VEHICLES_FAIL = 'GET_VEHICLES_FAIL';

