export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const CREATE_SUCCESS = 'CREATE_SUCCESS';
export const ERROR_RESET = 'ERROR_RESET';

export const SET_MOTORCARRIER = 'SET_MOTORCARRIER';
export const START_MCCREATE = 'START_MCCREATE';
export const CREATEMC_SUCCESS = 'CREATEMC_SUCCESS';
export const MCARRIER_CREATE_FAIL = 'CREATEMC_SUCCESS';

export const GET_USERS_START = 'GET_USERS_START';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';
export const USER_DELETE = 'USER_DELETE';
export const DEL_ERROR_RESET = 'DEL_ERROR_RESET';
export const CREATE_USER = 'CREATE_USER';

export const GET_VEHICLES_START = 'GET_VEHICLES_START';
export const GET_VEHICLES_SUCCESS = 'GET_VEHICLES_SUCCESS';
export const GET_VEHICLES_FAIL = 'GET_VEHICLES_FAIL';
export const DELETE_VEHICLE = 'DELETE_VEHICLE';
export const CREATE_VEHICLE = 'CREATE_VEHICLE';

export const GET_VEHICLE_START = 'GET_VEHICLE_START';
export const GET_VEHICLE_SUCCESS = 'GET_VEHICLE_SUCCESS';
export const GET_VEHICLE_FAIL = 'GET_VEHICLE_FAIL';
export const DELV_ERROR_RESET = 'DELV_ERROR_RESET';

export const GET_USER_INFO_START = 'GET_USER_INFO_START';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAIL = 'GET_USER_INFO_FAIL';

export const GET_USER_LOGS_START = 'GET_USER_LOGS_START';
export const GET_USER_LOGS_SUCCESS = 'GET_USER_LOGS_SUCCESS';
export const GET_USER_LOGS_FAIL = 'GET_USER_LOGS_FAIL';

export const GET_TRACKING_INFO_START = 'GET_TRACKING_INFO_START';
export const GET_TRACKING_INFO_SUCCESS = 'GET_TRACKING_INFO_SUCCESS';
export const GET_TRACKING_INFO_FAIL = 'GET_TRACKING_INFO_FAIL';

export const ADD_BREADCRUMBS = 'ADD_BREADCRUMBS';
export const RESET_BREADCRUMBS = 'RESET_BREADCRUMBS';
export const DELETE_CRUMBS = 'DELETE_CRUMBS';
export const POP_CRUMB = 'POP_CRUMB';

export const UPDATE_SIDEBAR = 'UPDATE_SIDEBAR';
export const UNMARK_SIDEBAR = 'UNMARK_SIDEBAR';

export const UPDATE_LASTMOD = 'UPDATE_LASTMOD';

export const UPDATE_USERS_START = 'UPDATE_USERS_START';
export const UPDATE_USERS_SUCCESS = 'UPDATE_USERS_SUCCESS';
export const UPDATE_USERS_FAIL = 'UPDATE_USERS_FAIL';

export const UPDATE_VEHICLES_START = 'UPDATE_VEHICLES_START';
export const UPDATE_VEHICLES_SUCCESS = 'UPDATE_VEHICLES_SUCCESS';
export const UPDATE_VEHICLES_FAIL = 'UPDATE_VEHICLES_FAIL';
