export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const CREATE_SUCCESS = 'CREATE_SUCCESS';
export const ERROR_RESET = 'ERROR_RESET';

export const SET_MOTORCARRIER = 'SET_MOTORCARRIER';
export const START_MCCREATE = 'START_MCCREATE';
export const CREATEMC_SUCCESS = 'CREATEMC_SUCCESS';
export const MCARRIER_CREATE_FAIL = 'CREATEMC_SUCCESS';

export const GET_USERS_START = 'GET_USERS_START';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';
export const DELETE_USER = 'DELETE_USER';
export const DEL_ERROR_RESET = 'DEL_ERROR_RESET';

export const GET_VEHICLES_START = 'GET_VEHICLES_START';
export const GET_VEHICLES_SUCCESS = 'GET_VEHICLES_SUCCESS';
export const GET_VEHICLES_FAIL = 'GET_VEHICLES_FAIL';
export const DELETE_VEHICLE = 'DELETE_VEHICLE';
export const DELV_ERROR_RESET = 'DELV_ERROR_RESET';

export const GET_USER_INFO_START = 'GET_USER_INFO_START';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAIL = 'GET_USER_INFO_FAIL';

export const GET_USER_LOGS_START = 'GET_USER_LOGS_START';
export const GET_USER_LOGS_SUCCESS = 'GET_USER_LOGS_SUCCESS';
export const GET_USER_LOGS_FAIL = 'GET_USER_LOGS_FAIL';
